### ISSUE TITLE
Add .avsc files extension support

### ISSUE THREAD

**Issue by svdimchenko** [anboralabs/json-crack-intellij#13]
Hi there! This extension works perfectly for `.json` files.

I work with many `.avsc` files which actually have the same structure https://avro.apache.org/docs/1.12.0/specification/. Now to enable lineage view I should rename the file from `file.avsc` to `file.json` to achieve it. It would be great to have some config where I can set the extensions list, which should be parsed as json.

**Comment by dalgarins** [comment]
![Screenshot 2024-11-15 at 9 23 51 AM](https://github.com/user-attachments/assets/e19b4b0d-9877-45fc-9389-764df383c352)

Jetbrains IDE allow you to add .avsc files as json files.

**Comment by svdimchenko** [comment]
@dalgarins thanks for advice. But in this case I get conflict with https://plugins.jetbrains.com/plugin/15728-avro-schema-support, which is super useful for avro schemas.

**Comment by dalgarins** [comment]
@svdimchenko ok I will work to try to add a new feature or integrate my plugin with Avro plugin.

**Comment by dalgarins** [comment]
@svdimchenko I have added a setting panel to add extensions.

![Screenshot 2024-11-23 at 9 59 03 AM](https://github.com/user-attachments/assets/8caf3e83-75ef-46de-980c-f2a21f3d6c8c)

![Screenshot 2024-11-23 at 9 59 48 AM](https://github.com/user-attachments/assets/a87c28ad-4202-497f-af37-b50c0c317687)
 
this feature will be available on version: 1.3.2

**Comment by svdimchenko** [comment]
hey @dalgarins thanks a lot for adding this feature, works as a charm 🚀
