### ISSUE TITLE
can't view jsoncrack

### ISSUE THREAD

**Issue by bluelovers** [anboralabs/json-crack-intellij#6]
![image](https://github.com/anboralabs/json-crack-intellij/assets/167966/53c19d18-fd5b-488c-bf7e-655558ec4f88)

**Comment by RipVampiretto** [comment]
I'm trying WebStorm recently as an alternative to my dear VSCode and I also have this problem, sigh, while it works without any kind of problem on VSCode

**Comment by guoyangqiao** [comment]
same problem using 2024.1 
![image](https://github.com/anboralabs/json-crack-intellij/assets/8182636/5f08b76d-1d95-4fef-8aa7-bed9cc39b4bb

**Comment by guoyangqiao** [comment]
@dalgarins Please consider addressing the fix for the issue.

**Comment by dalgarins** [comment]
@guoyangqiao I was not able to reproduce the issue, could you share your json file? to validate if something is wrong with that.

**Comment by guoyangqiao** [comment]
way to reproduce
create json file with below:
`{
  "reqNo": "1a72dde0bb5447c9889350c4fc722f1b",
  "respCode": "0000",
  "respMsg": "接口返回正常",
  "resultCode": "SUCCESS",
  "resultType": "SUCCESS",
  "success": true
}`
click JSON Crack, during the error page producing, left down corner producing error message
![17134102647211](https://github.com/anboralabs/json-crack-intellij/assets/8182636/5058aede-f7df-401b-bc89-36e9e9841d2d)

**Comment by dalgarins** [comment]
<img width="1124" alt="Screenshot 2024-04-20 at 5 11 56 PM" src="https://github.com/anboralabs/json-crack-intellij/assets/8527174/02bc2052-15b1-4584-8c97-a0ef40ae8a97">

@guoyangqiao thanks I was able to fix the issue on version 1.2.3, will be available this week.

**Comment by dalgarins** [comment]
New version is available, please download and test it, let me know if the issue is fixed to you.

**Comment by dalgarins** [comment]
@bluelovers , @RipVampiretto and @guoyangqiao the issue is fixed to you? In the new version.

**Comment by guoyangqiao** [comment]
seem it work  correctly now, very much thanks！
